name: Deploy to VPS

on:
  push:
    branches:
      - main  # Скрипт сработает только при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with rsync
        uses: Burnett01/rsync-deployments@7.0.0
        with:
          switches: -avz --delete
          path: ./ 
          remote_path: /var/www/aimyrtana/ # Укажите ПУТЬ к вашей папке на VPS
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.UBUNTU_AI_MYRTANA }}
